`timescale 1ns/1ps

module ff_av2_entropy_coder (
  input  logic        partition_active,
  input  logic        leaf_active,
  input  logic [63:0] low,
  input  logic [31:0] rng,
  input  logic signed [7:0] cnt,
  input  logic [2:0]  phase,
  input  logic [6:0]  step,
  input  logic [1:0]  partition,
  input  logic        partition_emit_do_split,
  input  logic        partition_emit_rect,
  input  logic [31:0] partition_do_cdf0,
  input  logic [31:0] partition_rect_cdf0,
  input  logic        ibc_use_copy,
  input  logic [1:0]  ibc_drl_idx,
  input  logic [1:0]  intrabc_ctx,
  input  logic [1:0]  intrabc_skip_ctx,
  input  logic [1:0]  leaf_luma_mode,
  input  logic        leaf_fsc_symbol,
  input  logic [31:0] leaf_fsc_fh,
  input  logic        palette_mode,
  input  logic        chroma_bdpcm_horz,
  input  logic        residual_mode,
  input  logic        leaf_luma_palette,
  input  logic        palette_op_valid,
  input  logic        palette_op_literal,
  input  logic [31:0] palette_op_literal_value,
  input  logic [4:0]  palette_op_literal_bits,
  input  logic [31:0] palette_op_fl,
  input  logic [31:0] palette_op_fh,
  input  logic [4:0]  palette_op_fl_inc,
  input  logic [4:0]  palette_op_fh_inc,
  input  logic        luma_residual_op_valid,
  input  logic        luma_residual_op_literal,
  input  logic [31:0] luma_residual_op_literal_value,
  input  logic [4:0]  luma_residual_op_literal_bits,
  input  logic [31:0] luma_residual_op_fl,
  input  logic [31:0] luma_residual_op_fh,
  input  logic [4:0]  luma_residual_op_fl_inc,
  input  logic [4:0]  luma_residual_op_fh_inc,
  input  logic        chroma_bdpcm_op_valid,
  input  logic        chroma_bdpcm_op_literal,
  input  logic [31:0] chroma_bdpcm_op_literal_value,
  input  logic [4:0]  chroma_bdpcm_op_literal_bits,
  input  logic [31:0] chroma_bdpcm_op_fl,
  input  logic [31:0] chroma_bdpcm_op_fh,
  input  logic [4:0]  chroma_bdpcm_op_fl_inc,
  input  logic [4:0]  chroma_bdpcm_op_fh_inc,
  input  logic [31:0] y_txb_nonzero_fh,
  input  logic [31:0] u_txb_nonzero_fh,
  input  logic [31:0] v_txb_nonzero_fh,
  input  logic [31:0] y_dc_sign_fl,
  input  logic [15:0] txb_index,
  input  logic [15:0] txb_count,
  input  logic        chroma_bdpcm_txb_done,
  input  logic        stack_empty,
  output logic        op_valid,
  output logic        op_last,
  output logic [1:0]  norm_push_count,
  output logic [15:0] norm_push0,
  output logic [15:0] norm_push1,
  output logic [63:0] norm_low,
  output logic [31:0] norm_rng,
  output logic signed [7:0] norm_cnt
);

  logic        op_literal_w;
  logic [31:0] op_literal_value_w;
  logic [4:0]  op_literal_bits_w;
  logic [31:0] op_fl_w;
  logic [31:0] op_fh_w;
  logic [4:0]  op_fl_inc_w;
  logic [4:0]  op_fh_inc_w;

  ff_av2_entropy_op_mux op_mux (
    .partition_active(partition_active),
    .leaf_active(leaf_active),
    .phase(phase),
    .step(step),
    .partition(partition),
    .partition_emit_do_split(partition_emit_do_split),
    .partition_emit_rect(partition_emit_rect),
    .partition_do_cdf0(partition_do_cdf0),
    .partition_rect_cdf0(partition_rect_cdf0),
    .ibc_use_copy(ibc_use_copy),
    .ibc_drl_idx(ibc_drl_idx),
    .intrabc_ctx(intrabc_ctx),
    .intrabc_skip_ctx(intrabc_skip_ctx),
    .leaf_luma_mode(leaf_luma_mode),
    .leaf_fsc_symbol(leaf_fsc_symbol),
    .leaf_fsc_fh(leaf_fsc_fh),
    .palette_mode(palette_mode),
    .chroma_bdpcm_horz(chroma_bdpcm_horz),
    .residual_mode(residual_mode),
    .leaf_luma_palette(leaf_luma_palette),
    .palette_op_valid(palette_op_valid),
    .palette_op_literal(palette_op_literal),
    .palette_op_literal_value(palette_op_literal_value),
    .palette_op_literal_bits(palette_op_literal_bits),
    .palette_op_fl(palette_op_fl),
    .palette_op_fh(palette_op_fh),
    .palette_op_fl_inc(palette_op_fl_inc),
    .palette_op_fh_inc(palette_op_fh_inc),
    .luma_residual_op_valid(luma_residual_op_valid),
    .luma_residual_op_literal(luma_residual_op_literal),
    .luma_residual_op_literal_value(luma_residual_op_literal_value),
    .luma_residual_op_literal_bits(luma_residual_op_literal_bits),
    .luma_residual_op_fl(luma_residual_op_fl),
    .luma_residual_op_fh(luma_residual_op_fh),
    .luma_residual_op_fl_inc(luma_residual_op_fl_inc),
    .luma_residual_op_fh_inc(luma_residual_op_fh_inc),
    .chroma_bdpcm_op_valid(chroma_bdpcm_op_valid),
    .chroma_bdpcm_op_literal(chroma_bdpcm_op_literal),
    .chroma_bdpcm_op_literal_value(chroma_bdpcm_op_literal_value),
    .chroma_bdpcm_op_literal_bits(chroma_bdpcm_op_literal_bits),
    .chroma_bdpcm_op_fl(chroma_bdpcm_op_fl),
    .chroma_bdpcm_op_fh(chroma_bdpcm_op_fh),
    .chroma_bdpcm_op_fl_inc(chroma_bdpcm_op_fl_inc),
    .chroma_bdpcm_op_fh_inc(chroma_bdpcm_op_fh_inc),
    .y_txb_nonzero_fh(y_txb_nonzero_fh),
    .u_txb_nonzero_fh(u_txb_nonzero_fh),
    .v_txb_nonzero_fh(v_txb_nonzero_fh),
    .y_dc_sign_fl(y_dc_sign_fl),
    .txb_index(txb_index),
    .txb_count(txb_count),
    .chroma_bdpcm_txb_done(chroma_bdpcm_txb_done),
    .stack_empty(stack_empty),
    .op_valid(op_valid),
    .op_literal(op_literal_w),
    .op_literal_value(op_literal_value_w),
    .op_literal_bits(op_literal_bits_w),
    .op_fl(op_fl_w),
    .op_fh(op_fh_w),
    .op_fl_inc(op_fl_inc_w),
    .op_fh_inc(op_fh_inc_w),
    .op_last(op_last)
  );

  ff_av2_range_coder_step range_coder_step (
    .low(low),
    .rng(rng),
    .cnt(cnt),
    .op_literal(op_literal_w),
    .op_literal_value(op_literal_value_w),
    .op_literal_bits(op_literal_bits_w),
    .op_fl(op_fl_w),
    .op_fh(op_fh_w),
    .op_fl_inc(op_fl_inc_w),
    .op_fh_inc(op_fh_inc_w),
    .norm_push_count(norm_push_count),
    .norm_push0(norm_push0),
    .norm_push1(norm_push1),
    .norm_low(norm_low),
    .norm_rng(norm_rng),
    .norm_cnt(norm_cnt)
  );

endmodule
