`timescale 1ns/1ps

module ff_av2_entropy_top (
  input  logic        partition_active,
  input  logic        leaf_active,
  input  logic [15:0] tile_width,
  input  logic [15:0] tile_height,
  input  logic [4:0]  block_row_mi,
  input  logic [4:0]  block_col_mi,
  input  logic [4:0]  block_w_mi,
  input  logic [4:0]  block_h_mi,
  input  logic [1:0]  partition,
  input  logic        partition_emit_step,
  input  logic [7:0]  partition_above_ctx,
  input  logic [7:0]  partition_left_ctx,
  input  logic [63:0] low,
  input  logic [31:0] rng,
  input  logic signed [7:0] cnt,
  input  logic [2:0]  phase,
  input  logic [6:0]  step,
  input  logic        ibc_use_copy,
  input  logic [1:0]  ibc_drl_idx,
  input  logic [1:0]  intrabc_ctx,
  input  logic [1:0]  intrabc_skip_ctx,
  input  logic [1:0]  leaf_luma_mode,
  input  logic        palette_mode,
  input  logic        chroma_bdpcm_horz,
  input  logic        residual_mode,
  input  logic        leaf_luma_palette,
  input  logic        palette_op_valid,
  input  logic        palette_op_literal,
  input  logic [31:0] palette_op_literal_value,
  input  logic [4:0]  palette_op_literal_bits,
  input  logic [31:0] palette_op_fl,
  input  logic [31:0] palette_op_fh,
  input  logic [4:0]  palette_op_fl_inc,
  input  logic [4:0]  palette_op_fh_inc,
  input  logic        luma_residual_op_valid,
  input  logic        luma_residual_op_literal,
  input  logic [31:0] luma_residual_op_literal_value,
  input  logic [4:0]  luma_residual_op_literal_bits,
  input  logic [31:0] luma_residual_op_fl,
  input  logic [31:0] luma_residual_op_fh,
  input  logic [4:0]  luma_residual_op_fl_inc,
  input  logic [4:0]  luma_residual_op_fh_inc,
  input  logic        chroma_bdpcm_op_valid,
  input  logic        chroma_bdpcm_op_literal,
  input  logic [31:0] chroma_bdpcm_op_literal_value,
  input  logic [4:0]  chroma_bdpcm_op_literal_bits,
  input  logic [31:0] chroma_bdpcm_op_fl,
  input  logic [31:0] chroma_bdpcm_op_fh,
  input  logic [4:0]  chroma_bdpcm_op_fl_inc,
  input  logic [4:0]  chroma_bdpcm_op_fh_inc,
  input  logic [31:0] y_txb_nonzero_fh,
  input  logic [31:0] u_txb_nonzero_fh,
  input  logic [31:0] v_txb_nonzero_fh,
  input  logic [31:0] y_dc_sign_fl,
  input  logic [15:0] txb_index,
  input  logic [15:0] txb_count,
  input  logic        chroma_bdpcm_txb_done,
  input  logic        stack_empty,
  output logic [4:0]  visible_rows_mi,
  output logic [4:0]  visible_cols_mi,
  output logic        block_visible,
  output logic [4:0]  block_half_w_mi,
  output logic [4:0]  block_half_h_mi,
  output logic [1:0]  chosen_partition,
  output logic        partition_need_do_split,
  output logic        partition_need_rect,
  output logic        partition_emit_do_split,
  output logic        partition_emit_rect,
  output logic [7:0]  partition_update_above,
  output logic [7:0]  partition_update_left,
  output logic        leaf_fsc_symbol,
  output logic [31:0] leaf_fsc_fh,
  output logic        op_valid,
  output logic        op_last,
  output logic [1:0]  norm_push_count,
  output logic [15:0] norm_push0,
  output logic [15:0] norm_push1,
  output logic [63:0] norm_low,
  output logic [31:0] norm_rng,
  output logic signed [7:0] norm_cnt
);

  logic        allowed_none_w;
  logic        allowed_horz_w;
  logic        allowed_vert_w;
  logic        forced_valid_w;
  logic [1:0]  forced_partition_w;
  logic        partition_emit_done_w;
  logic [5:0]  partition_split_ctx_w;
  logic [5:0]  partition_rect_ctx_w;
  logic [1:0]  partition_raw_ctx_w;
  logic [31:0] partition_do_cdf0_w;
  logic [31:0] partition_rect_cdf0_w;

  ff_av2_partition_controller partition_controller (
    .tile_width(tile_width),
    .tile_height(tile_height),
    .block_row_mi(block_row_mi),
    .block_col_mi(block_col_mi),
    .block_w_mi(block_w_mi),
    .block_h_mi(block_h_mi),
    .partition(partition),
    .partition_emit_step(partition_emit_step),
    .palette_mode(palette_mode),
    .partition_above_ctx(partition_above_ctx),
    .partition_left_ctx(partition_left_ctx),
    .visible_rows_mi(visible_rows_mi),
    .visible_cols_mi(visible_cols_mi),
    .block_visible(block_visible),
    .block_half_w_mi(block_half_w_mi),
    .block_half_h_mi(block_half_h_mi),
    .allowed_none(allowed_none_w),
    .allowed_horz(allowed_horz_w),
    .allowed_vert(allowed_vert_w),
    .forced_valid(forced_valid_w),
    .forced_partition(forced_partition_w),
    .chosen_partition(chosen_partition),
    .partition_need_do_split(partition_need_do_split),
    .partition_need_rect(partition_need_rect),
    .partition_emit_do_split(partition_emit_do_split),
    .partition_emit_rect(partition_emit_rect),
    .partition_emit_done(partition_emit_done_w),
    .partition_split_ctx(partition_split_ctx_w),
    .partition_rect_ctx(partition_rect_ctx_w),
    .partition_raw_ctx(partition_raw_ctx_w),
    .partition_update_above(partition_update_above),
    .partition_update_left(partition_update_left),
    .leaf_fsc_symbol(leaf_fsc_symbol),
    .leaf_fsc_fh(leaf_fsc_fh)
  );

  ff_av2_partition_cdf_lut partition_cdf_lut (
    .split_ctx(partition_split_ctx_w),
    .rect_ctx(partition_rect_ctx_w),
    .do_split_cdf0(partition_do_cdf0_w),
    .rect_type_cdf0(partition_rect_cdf0_w)
  );

  ff_av2_entropy_coder entropy_coder (
    .partition_active(partition_active),
    .leaf_active(leaf_active),
    .low(low),
    .rng(rng),
    .cnt(cnt),
    .phase(phase),
    .step(step),
    .partition(partition),
    .partition_emit_do_split(partition_emit_do_split),
    .partition_emit_rect(partition_emit_rect),
    .partition_do_cdf0(partition_do_cdf0_w),
    .partition_rect_cdf0(partition_rect_cdf0_w),
    .ibc_use_copy(ibc_use_copy),
    .ibc_drl_idx(ibc_drl_idx),
    .intrabc_ctx(intrabc_ctx),
    .intrabc_skip_ctx(intrabc_skip_ctx),
    .leaf_luma_mode(leaf_luma_mode),
    .leaf_fsc_symbol(leaf_fsc_symbol),
    .leaf_fsc_fh(leaf_fsc_fh),
    .palette_mode(palette_mode),
    .chroma_bdpcm_horz(chroma_bdpcm_horz),
    .residual_mode(residual_mode),
    .leaf_luma_palette(leaf_luma_palette),
    .palette_op_valid(palette_op_valid),
    .palette_op_literal(palette_op_literal),
    .palette_op_literal_value(palette_op_literal_value),
    .palette_op_literal_bits(palette_op_literal_bits),
    .palette_op_fl(palette_op_fl),
    .palette_op_fh(palette_op_fh),
    .palette_op_fl_inc(palette_op_fl_inc),
    .palette_op_fh_inc(palette_op_fh_inc),
    .luma_residual_op_valid(luma_residual_op_valid),
    .luma_residual_op_literal(luma_residual_op_literal),
    .luma_residual_op_literal_value(luma_residual_op_literal_value),
    .luma_residual_op_literal_bits(luma_residual_op_literal_bits),
    .luma_residual_op_fl(luma_residual_op_fl),
    .luma_residual_op_fh(luma_residual_op_fh),
    .luma_residual_op_fl_inc(luma_residual_op_fl_inc),
    .luma_residual_op_fh_inc(luma_residual_op_fh_inc),
    .chroma_bdpcm_op_valid(chroma_bdpcm_op_valid),
    .chroma_bdpcm_op_literal(chroma_bdpcm_op_literal),
    .chroma_bdpcm_op_literal_value(chroma_bdpcm_op_literal_value),
    .chroma_bdpcm_op_literal_bits(chroma_bdpcm_op_literal_bits),
    .chroma_bdpcm_op_fl(chroma_bdpcm_op_fl),
    .chroma_bdpcm_op_fh(chroma_bdpcm_op_fh),
    .chroma_bdpcm_op_fl_inc(chroma_bdpcm_op_fl_inc),
    .chroma_bdpcm_op_fh_inc(chroma_bdpcm_op_fh_inc),
    .y_txb_nonzero_fh(y_txb_nonzero_fh),
    .u_txb_nonzero_fh(u_txb_nonzero_fh),
    .v_txb_nonzero_fh(v_txb_nonzero_fh),
    .y_dc_sign_fl(y_dc_sign_fl),
    .txb_index(txb_index),
    .txb_count(txb_count),
    .chroma_bdpcm_txb_done(chroma_bdpcm_txb_done),
    .stack_empty(stack_empty),
    .op_valid(op_valid),
    .op_last(op_last),
    .norm_push_count(norm_push_count),
    .norm_push0(norm_push0),
    .norm_push1(norm_push1),
    .norm_low(norm_low),
    .norm_rng(norm_rng),
    .norm_cnt(norm_cnt)
  );

endmodule
