#!/usr/bin/env python3
"""Run a configurable synthesis smoke flow for FrameForge RTL."""

from __future__ import annotations

import argparse
import os
import shlex
import shutil
import subprocess
from pathlib import Path


DEFAULT_BOARD = Path("synth/boards/arty-z7-10.env")
DEFAULT_FILELIST = Path("synth/filelists/cabac_8x8.f")
DEFAULT_TOP = "ff_vvc_cabac_8x8_stream_body"
LOCAL_LICENSE = Path(".tools/Xilinx.lic")
LOCAL_VIVADO_ROOT = Path(".tools/Xilinx/Vivado")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board", type=Path, default=DEFAULT_BOARD)
    parser.add_argument("--filelist", type=Path, default=DEFAULT_FILELIST)
    parser.add_argument("--top", default=DEFAULT_TOP)
    parser.add_argument("--out-dir", type=Path, default=Path("synth/out"))
    parser.add_argument("--clock-mhz", type=float, default=None)
    parser.add_argument("--tool", choices=("yosys", "vivado"), default="yosys")
    parser.add_argument("--post-synth-smoke", action="store_true")
    args = parser.parse_args()

    board = load_env_file(args.board)
    out_dir = args.out_dir / board.get("BOARD_NAME", "board") / args.top
    out_dir.mkdir(parents=True, exist_ok=True)
    clock_mhz = args.clock_mhz or float(board.get("DEFAULT_CLOCK_MHZ", "50"))

    sources = read_filelist(args.filelist)
    if args.tool == "vivado":
        return run_vivado(board, args.top, sources, out_dir, clock_mhz)

    rc = run_yosys(board, args.top, sources, out_dir, clock_mhz)
    if rc != 0 or not args.post_synth_smoke:
        return rc
    return run_post_synth_smoke(args.top, out_dir)


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, sep, value = stripped.partition("=")
        if not sep:
            continue
        values[key.strip()] = os.environ.get(key.strip(), value.strip())
    return values


def read_filelist(path: Path) -> list[Path]:
    sources: list[Path] = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        sources.append(Path(stripped))
    return sources


def find_tool(name: str) -> str:
    local = Path(".tools/oss-cad-suite/bin") / name
    if local.exists():
        return str(local)
    found = shutil.which(name)
    if found:
        return found
    raise SystemExit(
        f"{name} was not found. Run `make synth-env` or set PATH/SYNTH_{name.upper()}."
    )


def find_local_vivado_settings() -> Path | None:
    env_setting = os.environ.get("VIVADO_SETTINGS") or os.environ.get("SYNTH_VIVADO_SETTINGS")
    if env_setting:
        candidate = Path(env_setting)
        if candidate.exists():
            return candidate
        raise SystemExit(f"Configured Vivado settings script does not exist: {candidate}")

    candidates = sorted(LOCAL_VIVADO_ROOT.glob("*/settings64.sh"), reverse=True)
    return candidates[0] if candidates else None


def find_project_vivado_settings() -> Path | None:
    candidates = sorted(LOCAL_VIVADO_ROOT.glob("*/settings64.sh"), reverse=True)
    return candidates[0] if candidates else None


def find_vivado_command() -> list[str]:
    explicit = os.environ.get("SYNTH_VIVADO") or os.environ.get("VIVADO")
    if explicit:
        return [explicit]

    found = shutil.which("vivado")
    if found:
        return [found]

    local_bins = sorted(LOCAL_VIVADO_ROOT.glob("*/bin/vivado"), reverse=True)
    if local_bins:
        return [str(local_bins[0])]

    settings = find_project_vivado_settings()
    if settings:
        return ["bash", "-lc", f"source {shlex.quote(str(settings))} >/dev/null && exec vivado \"$@\"", "vivado"]

    raise SystemExit(
        "vivado was not found. Install Vivado under .tools/Xilinx, set VIVADO_SETTINGS, "
        "set SYNTH_VIVADO, or place vivado on PATH."
    )


def vivado_environment() -> dict[str, str]:
    env = os.environ.copy()
    if "XILINXD_LICENSE_FILE" not in env and LOCAL_LICENSE.exists():
        env["XILINXD_LICENSE_FILE"] = str(LOCAL_LICENSE.resolve())
    return env


def run_yosys(
    board: dict[str, str],
    top: str,
    sources: list[Path],
    out_dir: Path,
    clock_mhz: float,
) -> int:
    yosys = os.environ.get("SYNTH_YOSYS") or find_tool("yosys")
    family = board.get("FPGA_FAMILY", "xc7")
    script = out_dir / "synth_xilinx.ys"
    post_synth = out_dir / f"{top}.post_synth.v"
    json_netlist = out_dir / f"{top}.json"
    log = out_dir / "yosys.log"

    script.write_text(
        "\n".join(
            [
                "# Generated by scripts/run_synth.py",
                *[f"read_verilog -sv {quote_path(source)}" for source in sources],
                f"hierarchy -check -top {top}",
                "proc",
                "opt",
                "fsm",
                "opt",
                "memory",
                "opt",
                f"synth_xilinx -family {family} -top {top}",
                "stat -tech xilinx",
                f"write_json {quote_path(json_netlist)}",
                f"write_verilog -noattr {quote_path(post_synth)}",
                "",
            ]
        )
    )

    print(f"Synthesizing {top} for {board.get('BOARD_NAME')} ({board.get('FPGA_PART')})")
    print(f"Clock target metadata: {clock_mhz:g} MHz")
    print(f"Yosys script: {script}")
    with log.open("w") as log_file:
        completed = subprocess.run([yosys, "-s", str(script)], text=True, stdout=log_file, stderr=subprocess.STDOUT)
    print(f"Yosys log: {log}")
    print(f"Post-synth netlist: {post_synth}")
    return completed.returncode


def run_vivado(
    board: dict[str, str],
    top: str,
    sources: list[Path],
    out_dir: Path,
    clock_mhz: float,
) -> int:
    vivado_cmd = find_vivado_command()

    tcl = out_dir / "vivado_synth.tcl"
    period_ns = 1000.0 / clock_mhz
    part = board.get("FPGA_PART", "xc7z010clg400-1")
    tcl.write_text(
        "\n".join(
            [
                f"set part {part}",
                f"set top {top}",
                f"set out_dir {out_dir}",
                "create_project -in_memory -part $part",
                *[f"read_verilog -sv {quote_tcl_path(source)}" for source in sources],
                "set_property top $top [current_fileset]",
                "synth_design -top $top -part $part",
                f"create_clock -name ff_synth_clk -period {period_ns:.3f} [get_ports clk]",
                "report_utilization -file $out_dir/vivado_utilization.rpt",
                "report_timing_summary -file $out_dir/vivado_timing_summary.rpt",
                "write_verilog -force $out_dir/${top}.vivado_post_synth.v",
                "exit",
                "",
            ]
        )
    )
    log = out_dir / "vivado.log"
    print(f"Running Vivado synthesis for {top} on {part}")
    if "XILINXD_LICENSE_FILE" not in os.environ and LOCAL_LICENSE.exists():
        print(f"Using project-local Vivado license: {LOCAL_LICENSE}")
    settings = find_project_vivado_settings()
    if settings:
        print(f"Detected project-local Vivado settings: {settings}")
    with log.open("w") as log_file:
        completed = subprocess.run(
            [*vivado_cmd, "-mode", "batch", "-source", str(tcl)],
            env=vivado_environment(),
            text=True,
            stdout=log_file,
            stderr=subprocess.STDOUT,
        )
    print(f"Vivado log: {log}")
    return completed.returncode


def run_post_synth_smoke(top: str, out_dir: Path) -> int:
    if top != DEFAULT_TOP:
        print(f"Post-synth smoke is only wired for {DEFAULT_TOP}; skipping {top}.")
        return 0

    iverilog = os.environ.get("SYNTH_IVERILOG") or find_tool("iverilog")
    vvp = os.environ.get("SYNTH_VVP") or find_tool("vvp")
    yosys_config = os.environ.get("SYNTH_YOSYS_CONFIG") or find_tool("yosys-config")
    datdir = subprocess.check_output([yosys_config, "--datdir"], text=True).strip()
    cells_sim = Path(datdir) / "xilinx" / "cells_sim.v"
    netlist = out_dir / f"{top}.post_synth.v"
    tb = out_dir / "post_synth_smoke_tb.v"
    sim = out_dir / "post_synth_smoke.vvp"

    tb.write_text(
        """
`timescale 1ns/1ps
module post_synth_smoke_tb;
  reg clk = 1'b0;
  reg rst_n = 1'b0;
  reg start = 1'b0;
  reg clear = 1'b0;
  reg [4:0] luma_rem = 5'd16;
  reg [4:0] cb_rem = 5'd16;
  reg m_axis_ready = 1'b1;
  wire m_axis_valid;
  wire [7:0] m_axis_data;
  wire m_axis_last;
  wire [2:0] stream_last_byte_bits;
  wire done;
  integer cycles = 0;

  always #5 clk = ~clk;

  ff_vvc_cabac_8x8_stream_body dut (
    .clk(clk), .rst_n(rst_n), .start(start), .clear(clear),
    .luma_rem(luma_rem), .cb_rem(cb_rem),
    .m_axis_ready(m_axis_ready), .m_axis_valid(m_axis_valid),
    .m_axis_data(m_axis_data), .m_axis_last(m_axis_last),
    .stream_last_byte_bits(stream_last_byte_bits), .done(done)
  );

  initial begin
    repeat (4) @(posedge clk);
    rst_n <= 1'b1;
    @(posedge clk);
    start <= 1'b1;
    @(posedge clk);
    start <= 1'b0;
    while (!done && cycles < 512) begin
      cycles = cycles + 1;
      @(posedge clk);
    end
    if (!done) begin
      $display("FAIL: post-synth smoke timed out");
      $finish(1);
    end
    $display("PASS: post-synth smoke completed in %0d cycles", cycles);
    $finish(0);
  end
endmodule
"""
    )
    cmd = [iverilog, "-g2012", "-o", str(sim), str(cells_sim), str(netlist), str(tb)]
    print("Compiling post-synth smoke simulation")
    subprocess.run(cmd, check=True)
    print("Running post-synth smoke simulation")
    return subprocess.run([vvp, str(sim)], check=False).returncode


def quote_path(path: Path) -> str:
    return shlex.quote(str(path))


def quote_tcl_path(path: Path) -> str:
    return "{" + str(path) + "}"


if __name__ == "__main__":
    raise SystemExit(main())
